#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 08, 2018 07:53:06 PM CET  platform: Linux

import sys
from main import *

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import conf_ui_support


MIXING_TYPES = [1, 2, 3, 4]
MUTATION_PERCENTAGE = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, top, root
    root = tk.Tk()
    conf_ui_support.set_Tk_var()
    top = Window(root)
    top.old_matrix_checkbox.select()
    top.select_old()
    conf_ui_support.init(root, top)
    root.mainloop()


top = None


def create_window(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global top, w_win, rt
    rt = root
    top = tk.Toplevel(root)
    conf_ui_support.set_Tk_var()
    window = Window(top)
    conf_ui_support.init(top, window, *args, **kwargs)
    return (top, window)


def destroy_window():
    global top
    top.destroy()
    top = None


class Window:
    def __init__(self, top=None):
        self.engine = Engine()
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {DejaVu Sans} -size 12 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {DejaVu Sans} -size 13 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=[('selected', _compcolor), ('active',_ana2color)])

        top.geometry("490x684+637+138")
        top.title("Comi Voyager")

        self.price_conf_lbl = tk.Label(top)
        self.price_conf_lbl.place(relx=0.224, rely=0.029, height=20, width=262)
        self.price_conf_lbl.configure(font=font9)
        self.price_conf_lbl.configure(text='''Price matrix configuration''')
        self.price_conf_lbl.configure(width=262)

        self.old_matrix_checkbox = tk.Checkbutton(top)
        self.old_matrix_checkbox.place(relx=0.041, rely=0.088, relheight=0.034, relwidth=0.41)
        self.old_matrix_checkbox.configure(justify='left')
        self.old_matrix_checkbox.configure(text='''Load previous price matrix''')
        self.old_matrix_checkbox.configure(command=self.select_old)

        self.new_matrix_checkbox = tk.Checkbutton(top)
        self.new_matrix_checkbox.place(relx=0.531, rely=0.088, relheight=0.034, relwidth=0.376)
        self.new_matrix_checkbox.configure(justify='left')
        self.new_matrix_checkbox.configure(text='''Create new price matrix''')
        self.new_matrix_checkbox.configure(command=self.select_new)

        self.num_of_cities_entry = tk.Entry(top)
        self.num_of_cities_entry.place(relx=0.755, rely=0.146, height=23, relwidth=0.196)
        self.num_of_cities_entry.configure(background="white")
        self.num_of_cities_entry.configure(font="TkFixedFont")
        self.num_of_cities_entry.configure(width=96)
        self.num_of_cities_entry.setvar(value=self.engine.num_of_cities)

        self.num_of_cities_lbl = tk.Label(top)
        self.num_of_cities_lbl.place(relx=0.551, rely=0.146, height=21, width=91)

        self.num_of_cities_lbl.configure(text='''Num of cities''')

        self.min_price_entry = tk.Entry(top)
        self.min_price_entry.place(relx=0.755, rely=0.19, height=23, relwidth=0.196)
        self.min_price_entry.configure(background="white")
        self.min_price_entry.configure(font="TkFixedFont")
        self.min_price_entry.configure(width=96)

        self.max_price_entry = tk.Entry(top)
        self.max_price_entry.place(relx=0.755, rely=0.234, height=23, relwidth=0.196)
        self.max_price_entry.configure(background="white")
        self.max_price_entry.configure(cursor="fleur")
        self.max_price_entry.configure(font="TkFixedFont")
        self.max_price_entry.configure(width=96)

        self.min_price_lbl = tk.Label(top)
        self.min_price_lbl.place(relx=0.551, rely=0.19, height=21, width=64)
        self.min_price_lbl.configure(text='''Min price''')

        self.max_price_lbl = tk.Label(top)
        self.max_price_lbl.place(relx=0.551, rely=0.234, height=21, width=68)
        self.max_price_lbl.configure(text='''Max price''')

        self.generate_new_matrix_btn = tk.Button(top)
        self.generate_new_matrix_btn.place(relx=0.653, rely=0.292, height=31, width=98)
        self.generate_new_matrix_btn.configure(background="#ef2943")
        self.generate_new_matrix_btn.configure(cursor="fleur")
        self.generate_new_matrix_btn.configure(text='''Generate''')
        self.generate_new_matrix_btn.configure(width=98)
        self.generate_new_matrix_btn.configure(command=self.generate_price_matrix)

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.49, rely=0.088, relheight=0.263)
        self.TSeparator1.configure(orient="vertical")

        self.gen_alg_conf_lbl = tk.Label(top)
        self.gen_alg_conf_lbl.place(relx=0.163, rely=0.512, height=26, width=287)

        self.gen_alg_conf_lbl.configure(font=font9)
        self.gen_alg_conf_lbl.configure(text='''Generic Algorithm configuration''')

        self.run_simple_solution_btn = tk.Button(top)
        self.run_simple_solution_btn.place(relx=0.735, rely=0.395, height=31, width=53)
        self.run_simple_solution_btn.configure(background="#d8a720")
        self.run_simple_solution_btn.configure(cursor="fleur")
        self.run_simple_solution_btn.configure(text='''Run''')
        self.run_simple_solution_btn.configure(command=self.engine.main)

        self.simple_solution_lbl = tk.Label(top)
        self.simple_solution_lbl.place(relx=0.122, rely=0.395, height=31, width=295)
        self.simple_solution_lbl.configure(text='''Run simple solution, not generic algorithms''')
        self.simple_solution_lbl.configure(width=295)

        self.population_size_lbl = tk.Label(top)
        self.population_size_lbl.place(relx=0.041, rely=0.57, height=21, width=103)
        self.population_size_lbl.configure(text='''Population size''')

        self.mixing_type_lbl = tk.Label(top)
        self.mixing_type_lbl.place(relx=0.49, rely=0.57, height=21, width=100)
        self.mixing_type_lbl.configure(text='''Mixing type''')
        self.mixing_type_lbl.configure(width=100)

        self.population_size_entry = tk.Entry(top)
        self.population_size_entry.place(relx=0.286, rely=0.57, height=23, relwidth=0.135)
        self.population_size_entry.configure(background="white")
        self.population_size_entry.configure(font="TkFixedFont")
        self.population_size_entry.configure(width=66)

        self.mixing_type_box = ttk.Combobox(top, values=MIXING_TYPES)
        self.mixing_type_box.place(relx=0.694, rely=0.57, relheight=0.031, relwidth=0.137)
        # self.mixing_type_box.configure(textvariable=conf_ui_support.combobox)
        self.mixing_type_box.configure(width=67)
        self.mixing_type_box.configure(background="#000000")
        self.mixing_type_box.configure(takefocus="")
        self.mixing_type_box.configure(cursor="fleur")

        self.mutation_percentage_lbl = tk.Label(top)
        self.mutation_percentage_lbl.place(relx=0.041, rely=0.614, height=21, width=79)
        self.mutation_percentage_lbl.configure(text='''Mutation %''')

        self.mutation_percentage_box = ttk.Combobox(top, values=MUTATION_PERCENTAGE)
        self.mutation_percentage_box.place(relx=0.286, rely=0.614, relheight=0.031, relwidth=0.137)
        # self.mutation_percentage_box.configure(textvariable=conf_ui_support.combobox)
        self.mutation_percentage_box.configure(width=67)
        self.mutation_percentage_box.configure(takefocus="")

        self.Label10 = tk.Label(top)
        self.Label10.place(relx=0.347, rely=0.702, height=23, width=118)
        self.Label10.configure(font=font10)
        self.Label10.configure(text='''Stop condition''')

        self.static_stop_checkbox = tk.Checkbutton(top)
        self.static_stop_checkbox.place(relx=0.204, rely=0.746, relheight=0.034, relwidth=0.131)
        self.static_stop_checkbox.configure(justify='left')
        self.static_stop_checkbox.configure(text='''Static''')
        self.static_stop_checkbox.configure(variable=conf_ui_support.che79)

        self.dynamic_stop_checkbox = tk.Checkbutton(top)
        self.dynamic_stop_checkbox.place(relx=0.531, rely=0.746, relheight=0.034, relwidth=0.173)
        self.dynamic_stop_checkbox.configure(justify='left')
        self.dynamic_stop_checkbox.configure(text='''Dynamic''')
        self.dynamic_stop_checkbox.configure(variable=conf_ui_support.che80)

        self.menu_bar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu = self.menu_bar)

        self.generations_to_end_lbl = tk.Label(top)
        self.generations_to_end_lbl.place(relx=0.041, rely=0.789, height=21, width=79)
        self.generations_to_end_lbl.configure(text='''Gen. to end''')
        self.generations_to_end_lbl.configure(wraplength="80")

        self.generations_to_end_entry = tk.Entry(top)
        self.generations_to_end_entry.place(relx=0.224, rely=0.789, height=23, relwidth=0.176)
        self.generations_to_end_entry.configure(background="white")
        self.generations_to_end_entry.configure(font="TkFixedFont")
        self.generations_to_end_entry.configure(width=86)

        self.generations_range_lbl = tk.Label(top)
        self.generations_range_lbl.place(relx=0.551, rely=0.789, height=21, width=75)
        self.generations_range_lbl.configure(text='''Gen. range''')

        self.generations_range_entry = tk.Entry(top)
        self.generations_range_entry.place(relx=0.714, rely=0.789, height=23, relwidth=0.196)
        self.generations_range_entry.configure(background="white")
        self.generations_range_entry.configure(font="TkFixedFont")
        self.generations_range_entry.configure(width=96)

        self.delta_lbl = tk.Label(top)
        self.delta_lbl.place(relx=0.551, rely=0.833, height=21, width=39)
        self.delta_lbl.configure(text='''Delta''')

        self.delta_entry = tk.Entry(top)
        self.delta_entry.place(relx=0.714, rely=0.833, height=23, relwidth=0.135)

        self.delta_entry.configure(background="white")
        self.delta_entry.configure(cursor="fleur")
        self.delta_entry.configure(font="TkFixedFont")
        self.delta_entry.configure(width=66)

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.469, rely=0.76, relheight=0.132)
        self.TSeparator2.configure(orient="vertical")

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.265, rely=0.468, relwidth=0.408)

        self.TSeparator4 = ttk.Separator(top)
        self.TSeparator4.place(relx=0.265, rely=0.673, relwidth=0.408)

        self.run_generic_lbl = tk.Label(top)
        self.run_generic_lbl.place(relx=0.122, rely=0.936, height=21, width=156)
        self.run_generic_lbl.configure(text='''Run generic algorithm''')

        self.run_generic_btn = tk.Button(top)
        self.run_generic_btn.place(relx=0.49, rely=0.921, height=41, width=83)
        self.run_generic_btn.configure(background="#8dd868")
        self.run_generic_btn.configure(cursor="fleur")
        self.run_generic_btn.configure(text='''Run''')
        self.run_generic_btn.configure(width=83)

    def select_old(self):
        self.engine.create_new_prices = False
        self.new_matrix_checkbox.deselect()
        self.num_of_cities_entry.config(state="disabled")
        self.min_price_entry.config(state="disabled")
        self.max_price_entry.config(state="disabled")

    def select_new(self):
        self.engine.create_new_prices = True
        self.old_matrix_checkbox.deselect()
        self.num_of_cities_entry.config(state="normal")
        self.min_price_entry.config(state="normal")
        self.max_price_entry.config(state="normal")

    def generate_price_matrix(self):
        try:
            self.engine.num_of_cities = int(self.num_of_cities_entry.get())
            self.engine.min_price = int(self.min_price_entry.get())
            self.engine.max_price = int(self.max_price_entry.get())
            self.engine.generate_new_prices()
            print("helllo")
        except:
            print("Invalid values")


if __name__ == '__main__':
    vp_start_gui()





