#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Dec 13, 2018 09:31:49 PM CET  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


class UIAdditions:
    def __init__(self, top=None,
                 run_exact_solution=None,
                 generic_algorithm_solution=None):

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.49, rely=0.088, relheight=0.263)
        self.TSeparator1.configure(orient="vertical")

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.469, rely=0.76, relheight=0.132)
        self.TSeparator2.configure(orient="vertical")

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(relx=0.265, rely=0.468, relwidth=0.408)

        self.TSeparator4 = ttk.Separator(top)
        self.TSeparator4.place(relx=0.265, rely=0.673, relwidth=0.408)

        self.simple_solution_lbl = tk.Label(top)
        self.simple_solution_lbl.place(relx=0.122, rely=0.395, height=31, width=295)
        self.simple_solution_lbl.configure(activebackground="#f9f9f9")
        self.simple_solution_lbl.configure(text="Run simple solution, not generic algorithms")

        self.run_generic_lbl = tk.Label(top)
        self.run_generic_lbl.place(relx=0.122, rely=0.936, height=21, width=156)
        self.run_generic_lbl.configure(activebackground="#f9f9f9")
        self.run_generic_lbl.configure(text="Run generic algorithm")

        self.run_simple_solution_btn = tk.Button(top)
        self.run_simple_solution_btn.place(relx=0.735, rely=0.395, height=31, width=53)
        self.run_simple_solution_btn.configure(activebackground="#f9f9f9")
        self.run_simple_solution_btn.configure(background="#d8a720")
        self.run_simple_solution_btn.configure(text='''Run''')
        self.run_simple_solution_btn.configure(command=run_exact_solution)

        self.run_generic_btn = tk.Button(top)
        self.run_generic_btn.place(relx=0.49, rely=0.921, height=41, width=83)
        self.run_generic_btn.configure(activebackground="#f9f9f9")
        self.run_generic_btn.configure(background="#8dd868")
        self.run_generic_btn.configure(text="Run")
        self.run_generic_btn.configure(command=generic_algorithm_solution)


def set_Tk_var():
    global che51
    che51 = tk.StringVar()
    global che52
    che52 = tk.StringVar()
    global combobox
    combobox = tk.StringVar()
    global che79
    che79 = tk.StringVar()
    global che80
    che80 = tk.StringVar()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import main
    main.vp_start_gui()




